### ISSUE TITLE
Ganache/Mocha String Error Issue

### ISSUE THREAD

**Issue by aakilfernandes** [trufflesuite/ganache-core#1004]
Somewhere in ganache-cli (hard to tell where cause the error is in a build) there's an error being thrown thats a string. Usually this would just propogate and give an easy string message, but mocha can't handle string errors (it attempts to add a property that causes it to break).

```
TypeError: Cannot create property 'uncaught' on string 'abort({"message":"FailedTransaction: VM Exception while processing transaction: revert","error":{},"stack":"Error\n    at new FailedTransaction (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/testable-error/index.js:4:18)\n    at batch.parts.forEach (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ultralightbeam/lib/execute.js:52:35)\n    at Array.forEach (<anonymous>)\n    at ultralightbeam.provider.sendAsync (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ultralightbeam/lib/execute.js:41:17)\n    at process.nextTick (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:80089)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}). Build with -s ASSERTIONS=1 for more info.'
    at Runner.uncaught (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/mocha/lib/runner.js:730:16)
    at process.uncaught (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/mocha/lib/runner.js:843:10)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/node_modules/source-map-support/source-map-support.js:461:21)
    at process.C.process.emit (/Users/aakilfernandes/projects/evm-domains/protocol/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:29928)
    at process._fatalException (bootstrap_node.js:374:26)

```

## Your Environment
* Version used: 6.4.4
* NodeJS Version: 8.9.1
* Operating System and version (include distro if Linux): Mac OSX
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Closing as this is fixed in ganache@7.0.0-alpha.1!
