### ISSUE TITLE
Ganache shuts down abruptly when contract balance exceeds 2^256-1 wei

### ISSUE THREAD

**Issue by barakman** [trufflesuite/ganache-core#1012]
Ganache shuts down abruptly when contract balance exceeds 2^256-1 wei.
As a result, Truffle throws a `ECONNREFUSED` exception.

## Steps to Reproduce

File MyContract.sol:
```
pragma solidity 0.4.25;

contract MyContract {
    uint public balance;
    uint public value;
    function deposit() external payable {
        balance = address(this).balance;
        value = msg.value;
    }
}
```
File MyTest.js:
```
contract("MyTest", function(accounts) {
    it("test", async function() {
        const myContract = await artifacts.require("MyContract").new();
        await myContract.deposit({from: accounts[0], value: web3.toBigNumber(2).pow(255)});
        const balance1 = await myContract.balance();
        const value1 = await myContract.value();
        console.log();
        console.log(balance1.toFixed());
        console.log(value1.toFixed());
        await myContract.deposit({from: accounts[1], value: web3.toBigNumber(2).pow(255).plus(1)});
        const balance2 = await myContract.balance();
        const value2 = await myContract.value();
        console.log();
        console.log(balance2.toFixed());
        console.log(value2.toFixed());
    });
});
```
Ganache command-line:
```
ganache-cli --port=8545 --gasPrice=20000000000 --gasLimit=8000000
    --account=0x0000000000000000000000000000000000000000000000000000000000000001,0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    --account=0x0000000000000000000000000000000000000000000000000000000000000002,0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
Truffle configuration:
```
development: {
    host:       "127.0.0.1",
    port:       8545,
    network_id: "*",
    gasPrice:   100000000000,
    gas:        8000000
}
```
## Output
```
    Contract: MyTest test:
57896044618658097711785492504343953926634992332820282019728792003956564819968
57896044618658097711785492504343953926634992332820282019728792003956564819968
  1) Contract: MyTest test
  2) Contract: MyTest "after each" hook: after test for "test"

  0 passing (2s)
  2 failing

  1) Contract: MyTest
       test:
     Error: Invalid JSON RPC response: "Error: read ECONNRESET\n    at _errnoException (util.js:992:11)\n    at TCP.onread (net.js:618:25)"
      at ProviderError.ExtendableError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-error\index.js:10:1)
      at new ProviderError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\error.js:17:1)
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:71:1
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:129:1
      at exports.XMLHttpRequest.request.onreadystatechange (C:\...\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at exports.XMLHttpRequest.dispatchEvent (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:591:1)
      at setState (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:610:1)
      at exports.XMLHttpRequest.handleError (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:532:1)
      at ClientRequest.errorHandler (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:459:1)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: MyTest
       "after each" hook: after test for "test":
     Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n    at Object._errnoException (util.js:992:11)\n    at _exceptionWithHostPort (util.js:1014:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)"
      at ProviderError.ExtendableError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-error\index.js:10:1)
      at new ProviderError (C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\error.js:17:1)
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:71:1
      at C:\...\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:129:1
      at exports.XMLHttpRequest.request.onreadystatechange (C:\...\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at exports.XMLHttpRequest.dispatchEvent (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:591:1)
      at setState (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:610:1)
      at exports.XMLHttpRequest.handleError (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:532:1)
      at ClientRequest.errorHandler (C:\...\node_modules\truffle\build\webpack:\~\xmlhttprequest\lib\XMLHttpRequest.js:459:1)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
## Environment
- truffle v4.1.15
- ganache-cli v6.2.5
- node v8.11.2
- npm v6.4.1
- Windows 10

## Update

Oddly enough, this doesn't happen if I mask the two state-variable assignments:
```
// balance = address(this).balance;
// value = msg.value;
```
Or even if I change them into a single assignment, such as:
```
balance = address(this).balance - value = msg.value;
```

**Comment by leeftk** [comment]
There's nothing to define the behavior here and due to it being an extremely unlikely edge case we are going to close this as a wont fix. Thanks!
