### ISSUE TITLE
crashes after server closed and directory with persistent storage deleted

### ISSUE THREAD

**Issue by unao** [trufflesuite/ganache-core#187]
After upgrading to newest `develop` I started to experience random (~10% of time) crashes on server start. I use filesystem db.

Here is a stack trace:

```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (<project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:24)
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at done (<project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:17)
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at processNode (<project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at <project-root>/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at <project-root>/node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
    at <project-root>/node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at <project-root>/node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at <project-root>/node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
    at <project-root>/node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (<project-root>/node_modules/ganache-core/lib/database/filedown.js:27:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
```

**Comment by unao** [comment]
Initially I thought the crash happens on start as I started processes pretty one after another, but I think I pinned down the issue and it is related to: https://github.com/trufflesuite/ganache-core/pull/185. What seems to be the case is that even if `stopMining` as part of `server.close` was called, and close callback got called the processes _may_ be still active and tries to modify the directory content. When I delete the directory immediately on close callback the crash happens with ~10-25% probability. Now I am testing if the issue would happen if I postpone the directory deletion by time longer than the time block...

**Comment by seesemichaelj** [comment]
@unao Does the issue disappear for you after using the fixes in #185?

**Comment by seesemichaelj** [comment]
I'm going to assume this works now that #185 is merged. Thanks!

**Comment by mahmoudafer** [comment]
I think I'm having the same issue, you can see it [reported in ganache-cli](https://github.com/trufflesuite/ganache-cli/issues/600#issuecomment-748634902)
