### ISSUE TITLE
eth_unsubscribe causes TypeError

### ISSUE THREAD

**Issue by smoelius** [trufflesuite/ganache-core#213]
Here is an example log entry:
````
[9:47:13 PM] eth_unsubscribe
[9:47:13 PM] eth_unsubscribe
[9:47:13 PM]    > {
[9:47:13 PM]    >   "jsonrpc": "2.0",
[9:47:13 PM]    >   "id": 13,
[9:47:13 PM]    >   "method": "eth_unsubscribe",
[9:47:13 PM]    >   "params": [
[9:47:13 PM]    >     "0x07"
[9:47:13 PM]    >   ]
[9:47:13 PM]    > }
[9:47:14 PM]  <   {
[9:47:14 PM]  <     "id": 13,
[9:47:14 PM]  <     "jsonrpc": "2.0",
[9:47:14 PM]  <     "result": true
[9:47:14 PM]  <   }
[9:47:14 PM]  <   {
[9:47:14 PM]  <     "id": 13,
[9:47:14 PM]  <     "jsonrpc": "2.0",
[9:47:14 PM]  <     "error": {
[9:47:14 PM]  <       "message": "Cannot read property 'subscriptions' of undefined",
[9:47:14 PM]  <       "code": -32000,
[9:47:14 PM]  <       "data": {
[9:47:14 PM]  <         "stack": "TypeError: Cannot read property 'subscriptions' of undefined
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/lib/webSocketServer.js:98:47
    at Object.intermediary [as callback] (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/lib/provider.js:103:5)
    at self.engine.sendAsync (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/lib/provider.js:150:12)
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:152:9
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/async/internal/once.js:12:16
    at replenish (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/async/internal/eachOfLimit.js:61:25)
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/async/eachLimit.js:43:36)
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/async/internal/doLimit.js:9:16
    at end (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:127:5)
    at /tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:82:7
    at SubscriptionSubprovider.FilterSubprovider.uninstallFilter (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:222:3)
    at SubscriptionSubprovider.eth_unsubscribe (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:80:10)
    at SubscriptionSubprovider.handleRequest (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:132:12)
    at next (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)
    at DelayedBlockFilter.handleRequest (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:27:3)
    at next (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)
    at RequestFunnel.handleRequest (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)
    at next (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)
    at Web3ProviderEngine._handleAsync (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:103:3)
    at Timeout._onTimeout (/tmp/.mount_ganachV1Ea0e/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:87:12)
    at ontimeout (timers.js:469:11)",
[9:47:14 PM]  <         "name": "TypeError"
[9:47:14 PM]  <       }
[9:47:14 PM]  <     }
[9:47:14 PM]  <   }
````
Concerning `ganache-core/lib/webSocketServer.js:97`:
````
connection = self.connectionsBySubscriptionId[payload.params[0]];
````
It appears this line should be:
````
connection = self.connectionsBySubscriptionId[payload.params[0]].connection;
````

**Comment by davidmurdoch** [comment]
Thanks @smoelius for taking the time to file this issue! We're currently tracking this issue in #186.
