### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by mikeshultz** [trufflesuite/ganache-core#3]
Would be helpful to have build instructions for those that might want to contribute to the project.

**Comment by mikeshultz** [comment]
Taking a whack at it.

## Install dependencies

`npm install`

## Run 

`nodejs index.js`

However, getting this now with nodejs version 6.11.1: 

    $ nodejs index.js 
    module.js:597
      return process.dlopen(module, path._makeLong(filename));
                     ^
    
    Error: Module version mismatch. Expected 48, got 57.
        at Error (native)
        at Object.Module._extensions..node (module.js:597:18)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/mike/dev/ganache-core/node_modules/scrypt/index.js:3:20)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)

Working on it.

**Comment by benjamincburns** [comment]
Thanks for submitting this, @mikeshultz! Our README.md was updated to include build instructions quite some time ago. Let us know if they're not adequate for your needs!
