### ISSUE TITLE
Ganache crashes when estimating gas for a transaction

### ISSUE THREAD

**Issue by cag** [trufflesuite/ganache-core#433]
## Expected Behavior

Ganache doesn't crash. I've tried the same set of actions against `geth --dev` successfully.

## Current Behavior

Ganache crashes during a transaction(/gas estimation?) which otherwise works fine with `geth --dev` (requires some finagling and I haven't tried it with Parity dev mode or anything else yet).

## Steps to Reproduce (for bugs)

This is kind of gnarly to reproduce, as I haven't isolated the issue yet. I'll update this later to be more focused if I have some bandwidth to do so.

1. Run `node -e "require('.').server().listen(8545)"` in a clone of `ganache-core`.
2. In another terminal, clone https://github.com/gnosis/hg-first-decentralized-market and checkout the `update-deps` branch.
3. Run `npm i && npm run migrate && npm start`.
4. Navigate to http://localhost:8080, click "Approve Market Maker", and then select "Yes", enter an amount, and click "Buy".
5. Observe the following stack trace:

```
/path/to/ganache-core/lib/utils/gasEstimation.js:88
      rootBegin: steps.systemOps[begin][0],
                                       ^
TypeError: Cannot read property '0' of undefined
    at findRootScope (/path/to/ganache-core/lib/utils/gasEstimation.js:88:40)
    at getTotal (/path/to/ganache-core/lib/utils/gasEstimation.js:155:36)
    at getTotal (/path/to/ganache-core/lib/utils/gasEstimation.js:192:25)
    at /path/to/ganache-core/lib/utils/gasEstimation.js:42:21
    at /path/to/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:70:9
    at /path/to/ganache-core/node_modules/async/dist/async.js:969:16
    at next (/path/to/ganache-core/node_modules/async/dist/async.js:5225:18)
    at /path/to/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:160:13
    at /path/to/ganache-core/node_modules/merkle-patricia-tree/util.js:51:36
    at /path/to/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at done (/path/to/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:17)
    at /path/to/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /path/to/ganache-core/lib/database/levelupobjectadapter.js:110:7
    at /path/to/ganache-core/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/path/to/ganache-core/node_modules/async/dist/async.js:1064:13)
    at /path/to/ganache-core/node_modules/async/dist/async.js:969:16
    at /path/to/ganache-core/node_modules/level-sublevel/shell.js:53:51
    at /path/to/ganache-core/node_modules/level-sublevel/nut.js:109:13
    at /path/to/ganache-core/lib/database/filedown.js:64:7
    at /path/to/ganache-core/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/path/to/ganache-core/node_modules/async/dist/async.js:1064:13)
    at /path/to/ganache-core/node_modules/async/dist/async.js:969:16
```

What's strange is that there's a line `await lmsrMarketMaker.trade(...)` which causes Ganache to crash, but the same kind of transaction can be found many times in the test cases for https://github.com/gnosis/hg-market-makers, and there, Ganache has no issue with the test suite.

## Your Environment

* Version used: Ganache Core cba166610008262266a60908d7ab4eb20fd856be, truffle-contract@4.0.19
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node v11.15.0
* Operating System and version: Arch Linux
* Link to your project: https://github.com/gnosis/hg-first-decentralized-market
* Changesets which surfaced this behavior:
   - https://github.com/gnosis/hg-contracts/pull/24 -- I have tried removing the `gasleft` requirement addition from this changeset and recompiling, but the aforementioned behavior still persists with that change. This is peculiar because other than that, I don't believe there is a particularly significant change to the logic flow.
   - https://github.com/gnosis/hg-market-makers/pull/10
   - https://github.com/gnosis/hg-first-decentralized-market/pull/31 -- I've tried downgrading `truffle-contract` to `4.0.13` but that also didn't change anything. `web3` version has remained the same.

**Comment by cag** [comment]
The rewrite of the gas estimation logic in #435 resolves this issue.
