### ISSUE TITLE
System Error when running Ganache 1.3.0 on darwin

### ISSUE THREAD

**Issue by jkcomment** [trufflesuite/ganache-core#478]
PLATFORM: darwin
GANACHE VERSION: 1.3.0

EXCEPTION:
```
Error: nonce generation function failed or private key is invalid
    at Object.exports.ecsign (/node_modules/ganache-core/node_modules/ethereumjs-util/dist/index.js:369:23)
    at Transaction.sign (/node_modules/ganache-core/node_modules/ethereumjs-tx/es5/index.js:252:23)
    at Transaction.sign (/node_modules/ganache-core/lib/utils/transaction.js:260:10)
    at Transaction.hash (/node_modules/ganache-core/node_modules/ethereumjs-tx/fake.js:66:12)
    at Transaction.fakeHash [as hash] (/node_modules/ganache-core/lib/utils/transaction.js:17:51)
    at RuntimeError.combine (/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)
    at /node_modules/ganache-core/lib/blockchain_double.js:516:30
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:70:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at next (/node_modules/ganache-core/node_modules/async/dist/async.js:5225:18)
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:93:9
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:51:36
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at done (/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:17)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:7
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/node_modules/ganache-core/node_modules/async/dist/async.js:1064:13)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:53:51
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.3.0) with initial configuration: {"hostname":"127.0.0.1","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"default_balance_ether":100,"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"constantinople"}
T+23ms: Ganache started successfully!
T+23ms: Waiting for requests...
T+53082ms: net_version
T+53092ms: eth_accounts
T+53120ms: eth_call
T+53155ms: eth_call
T+53176ms: eth_accounts
T+53195ms: eth_sendTransaction
T+53237ms:   Transaction: 0x0b3a7aa3ff97a65cf53aa9ce381e8b597fef0568741b87f03ac9139c4c9b4713
T+53237ms:   Contract created: 0x16056b56914a430f850890bf4afeca1534943423
T+53237ms:   Gas usage: 277462
T+53237ms:   Block Number: 1
T+53237ms:   Block Time: Thu Feb 14 2019 17:18:30 GMT+0900 (JST)
T+53238ms: eth_newBlockFilter
T+53240ms: eth_getFilterChanges
T+53255ms: eth_getTransactionReceipt
T+53261ms: eth_getCode
T+53271ms: eth_uninstallFilter
T+53272ms: eth_sendTransaction
T+53320ms:   Transaction: 0x609860ac8ec719798fffd974b76eb23ee326ed71847ba6b37caa0daa195bfb36
T+53320ms:   Gas usage: 42008
T+53320ms:   Block Number: 2
T+53321ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53322ms: eth_getTransactionReceipt
T+53322ms: eth_accounts
T+53340ms: eth_sendTransaction
T+53375ms:   Transaction: 0x8ebc258da17459abf3d9fd2014521d038a23c515f5d9c77f63c4aa6d1c2d2ae5
T+53375ms:   Contract created: 0xf888fb02af3a87551d4dd05603c8fb2f9a4cae13
T+53375ms:   Gas usage: 252160
T+53375ms:   Block Number: 3
T+53376ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53378ms: eth_newBlockFilter
T+53379ms: eth_getFilterChanges
T+53379ms: eth_getTransactionReceipt
T+53398ms: eth_getCode
T+53416ms: eth_uninstallFilter
T+53418ms: eth_sendTransaction
T+53453ms:   Transaction: 0x297631d037e42f39ce890274838b135c946ecbadc7940d778eb84a39df379a82
T+53453ms:   Gas usage: 27008
T+53453ms:   Block Number: 4
T+53454ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53454ms: eth_getTransactionReceipt
T+128063ms: net_version
T+128073ms: eth_accounts
T+128100ms: eth_call
T+180683ms: net_version
T+180695ms: eth_accounts
T+180727ms: eth_call
T+279279ms: net_version
T+279289ms: eth_accounts
T+279315ms: eth_call
T+374971ms: net_version
T+374983ms: eth_accounts
T+375009ms: eth_call
T+421208ms: net_version
T+421221ms: eth_accounts
T+421260ms: eth_call
T+482570ms: net_version
T+482579ms: eth_accounts
T+482604ms: eth_call
T+553401ms: net_version
T+553410ms: eth_accounts
T+553438ms: eth_call
T+603332ms: net_version
T+603342ms: eth_accounts
T+603371ms: eth_call
T+673503ms: net_version
T+673512ms: eth_accounts
T+673539ms: eth_call
T+704170ms: net_version
T+704187ms: eth_accounts
T+704205ms: eth_call
T+785463ms: net_version
T+785473ms: eth_accounts
T+785498ms: eth_call
T+794273ms: eth_call
T+794296ms: eth_getCode
T+831727ms: net_version
T+831739ms: eth_accounts
T+831768ms: eth_call
T+857986ms: net_version
T+857995ms: eth_accounts
T+858020ms: eth_call
T+953989ms: net_version
T+953998ms: eth_accounts
T+954023ms: eth_call
T+966437ms: eth_call
T+966462ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
@YanB25, any updates on reproduction steps?

**Comment by fabioberger** [comment]
Just hit this as well:

```
HD Wallet
==================
Mnemonic:      concert load couple harbor equip island argue ramp clarify fence smart topic
Base HD Path:  m/44'/60'/0'/0/{account_index}

Gas Price
==================
20000000000

Gas Limit
==================
10000000

Listening on 0.0.0.0:8545
eth_call
Error: nonce generation function failed or private key is invalid
    at Object.t.sign (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:264461)
    at Object.sign (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:253479)
    at Object.t.ecsign (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:17296)
    at e.sign (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:88084)
    at e.sign (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:84960)
    at e.hash (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:9536)
    at e.d [as hash] (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:82139)
    at o.combine (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:81172)
    at new o (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:80848)
    at Function.o.fromResults (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:81931)
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:121203
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1833282
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124
    at i (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41179)
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1190532
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:105418
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:392
    at c (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:5407)
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:317
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1851708
    at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:23237
    at o (/usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26646)
```

Platform: Docker `mhart/alpine-node:10`
Version: Ganache CLI v6.4.1

I was able to fix the issue by supplying a `From` address when making the `eth_call`.

**Comment by davidmurdoch** [comment]
@fabioberger can you try ganache-cli v6.7.0 and let me know if it's still an issue for you?

**Comment by feuGeneA** [comment]
@davidmurdoch I'm working with the same contracts and tests as @fabioberger , and I just reproduced this using ganache-cli v6.7.0.  My platform is Debian 4.9.130-2 (2018-10-27) x86_64

**Comment by fabioberger** [comment]
I was able to reproduce with Ganache CLI v6.8.2 (ganache-core: 2.9.2)
