### ISSUE TITLE
`eth_estimateGas` returns too low value when value is passed to a CALL

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [trufflesuite/ganache-core#486]
I was previously getting `out of gas` error which was resolved by following [this](https://github.com/trufflesuite/ganache-cli/issues/447) issue. Now i installed `ganache-cli@v7.0.0-beta.0` . It creates ethereum accounts on localhost if i write the following command;

> ganache-cli

The accounts on local host are as follows. If i use these accounts i didn't get out of gas error.

```
Ganache CLI v7.0.0-beta.0 (ganache-core: 3.0.0-beta.0)

Available Accounts
==================
(0) 0x83086809b44625886bf2481c5892c1e882f5920c
(1) 0x1870a73b1cb795abb22e19eadfdaf38caef95bf7
(2) 0x2e0cd765b452834b521c93ab50196b024e86d468
(3) 0x9cd2ed6a814c673b523ac66de105f23a9d878538
(4) 0x9450eb5ee9edf0f9d9c5d1703a6c0f9740562762
(5) 0x6ed0d10d0dbc6f56d7df0c94858f80cb358d405e
(6) 0x9126102c8a67f5d6a89701c5ea1bfa764dc4e986
(7) 0xaf7e7565e8c48e12533e68915385f451e1edbaa0
(8) 0x6de462fd093b02d98f07804288e0e877a26655c0
(9) 0x95f999fd73311ed14bfb2318e336d6148d449ceb

Private Keys
==================
(0) 5c4539b82cf105ec2a0f14624ac89f8afef1b57e502ce3536a73b2c195080bb0
(1) b72a92b9bdd61ae616af8c259c53cc8b561371efde43675976edd893298eb5fb
(2) 61ce20461dd2dd6f9c60c075573e66a05228289c73a04fd50579a8567b75ea09
(3) c289c54194c0b7b5fb7352652518c404edfe121fa4be6de09221048f05ba990e
(4) dd53b427292a10ca8d1ab764d64de9d30a3d1f7f1efdb717a287a4100e658f67
(5) f5967273d55c9af91541d3abe8cf5c0ce88b2f5bdfba49e3f86deff9bf85ef85
(6) 8649abe4a2c96e48e766807dd3e5d355151dfbd0b6fdc8cd3d1dcf19ba73dd64
(7) 0a9c79a4e6dc247242ccc8104d47357ad197b5ab1764277964c95625a49a9e4b
(8) 9a8ab7807ca7a34e0eb58f546790ce5b1db8351c5972957eebb542ced3ff7b54
(9) 5acd77d7bd6ddf15db71cdcc7749cfafab1eb179065f5ef5d7416e577cf080cb

HD Wallet
==================
Mnemonic:      install bargain breeze address giggle hurdle save grab network usual obscure wide
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
```

But now the **problem** is that i can not find any command for `ganache-cli`  to create these accounts on the wifi like we create the accounts using ganache application as follows;

![image](https://user-images.githubusercontent.com/41861952/65119855-2eb84d00-da06-11e9-9fb1-6753eafb62ee.png)

Is there any way to link the `ganache-cli@v7.0.0-beta.0` to the actual ganache application or is there any command on `ganache-cli` to create accounts on wifi instead of local host.

**My Enviroment:**

- ganache-cli@v7.0.0-beta.0
- npm v6.9.0
- Node v10.16.1
- ganache application version 2.1.1
- Remix appVersion=0.7.7

**Comment by ZeeshanAhmadKhalil** [comment]
I doesn't get any `out of gas` error when I used `ganache-cli@v7.0.0-beta.0`. This error is caused in `ganache-cli@6.7.0` so to reproduce the `out of gas` error I again installed `ganache-cli@6.7.0` by the following command;

> npm install -g ganache-cli@6.7.0
```
C:\Users\mk141\AppData\Roaming\npm\ganache-cli -> C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\cli.js

> keccak@1.4.0 install C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\keccak
> node-gyp rebuild


C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\keccak
gyp ERR! node -v v10.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mk141\AppData\Roaming\npm-cache\_logs\2019-09-19T09_16_40_561Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.7.1 install C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\secp256k1
> node-gyp rebuild


C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mk141\AppData\Roaming\npm\node_modules\ganache-cli\node_modules\secp256k1
gyp ERR! node -v v10.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mk141\AppData\Roaming\npm-cache\_logs\2019-09-19T09_16_42_375Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."
+ ganache-cli@6.7.0
added 23 packages from 31 contributors, removed 274 packages and updated 30 packages in 13.6s
```

To create the eth accounts I used the following command;

> ganache-cli
```
Ganache CLI v6.7.0 (ganache-core: 2.8.0)

Available Accounts
==================
(0) 0x9d9B2281d9a5aFdb416455514be0072688f2a5ea (100 ETH)
(1) 0xE8887950BF5C6499164FEfe907c84354b7449771 (100 ETH)
(2) 0x508073e5590D851C402e5847dDFAC732c9f13147 (100 ETH)
(3) 0xC49c43eC7547B405Ab9C56A914856ec4ECd88E1e (100 ETH)
(4) 0xB42FacBCbA2A5cDed5bbdE685D72e09E5fe29dF0 (100 ETH)
(5) 0x0304ACda55DA148be3a7e70C9496cddEf5aB084c (100 ETH)
(6) 0x9d2E8848E767B3e35369894826DEeC62ff5d966f (100 ETH)
(7) 0x3F728F04dAc6B1c0a154322F18918947802EB422 (100 ETH)
(8) 0xb705243Fd99B5b46F2db0C8014FD899d4Eb3654F (100 ETH)
(9) 0x6c73c7252B35bC6afeB58bBf99D7c4FdF4A52cEE (100 ETH)

Private Keys
==================
(0) 0xfde0c739047be6f633268399ab4c8a1f9035683f1c32baea477cf898f1fd1717
(1) 0x12f80c5178c8a114ca2ccbd9dfcc9512c1d567fb34cc79d2801ebc66756baf29
(2) 0xadd9fc65b80c8fe3db98c6bd2d92b5d3624aa6982365d4d21893af8c6b3c924c
(3) 0xbbabad905b57e1c29974d83bc71b5953013894d791ef7f60648d6867c25ebbd4
(4) 0x22ae61a77a1f65f1f89877d505d3074024159e156712cbeb37f248990464adf6
(5) 0x596dd0d5640ea250e72b3bfc2bcdb0057e237bdf8a45d89e9ba76845f74ea192
(6) 0xd60fd725ee3c80e1fb902110392ff34db12c28b45a49d9f4670301558a65aa89
(7) 0x3a2138d8736735abe7f15363ccbd314e86fdef45462cf3bf91b7fd4ea93d37f0
(8) 0xf2baae6a09bfec074b55c2c6dfbe44c48a82f69079180a63f9d141f33bf9cac6
(9) 0xdc5d980328b226c4bdb894cc2cbe08c3213be15840f714f098444d3a807eaab1

HD Wallet
==================
Mnemonic:      robust faint elephant emerge beach cause connect steel denial aim acid crash
Base HD Path:  m/44'/60'/0'/0/{account_index}

Gas Price
==================
20000000000

Gas Limit
==================
6721975

Listening on 127.0.0.1:8545
```
Now accounts are created on `http://127.0.0.1:8545`. I used one of there accounts to deploy the following smart contracts in [Remix](http://remix.ethereum.org/#appVersion=0.7.7&optimize=false&version=soljson-v0.5.1+commit.c8a2cb62.js) by using custom web3 provider.

```
pragma solidity >=0.4.0 <0.6.0;
contract Ether_Transfer_To{
    function () external payable { //fallback function
        
    }
    function get_balance() public returns(uint){
        return address(this).balance;
    }
}
contract Ether_Transfer_From{
    Ether_Transfer_To private the_instance;
    constructor() public{
        //the_instance=Ether_Transfer_To(address(this));
        the_instance=new Ether_Transfer_To();
    }
    function get_balance() public returns(uint){
        return address(this).balance;
    }
    function get_balance_of_instance() public returns(uint){
        //return address(the_instance).balance;
        return the_instance.get_balance();
    }
    function () external payable {
        // msg.sender.send(msg.value)
        // address(the_instance).send(msg.value);
        address(the_instance).transfer(msg.value);
    }
}
```

Whenever I try to send 1 eth from account to `Ether_Transfer_From` contract by writing 1 in the textbox and clicking on (fallback) I get the following error;

`errored: VM Exception while processing transaction: out of gas`

![image](https://user-images.githubusercontent.com/41861952/65232677-fc345000-daea-11e9-9805-f13d02be329e.png)

**Comment by ZeeshanAhmadKhalil** [comment]
I can create eth accounts on WiFi by using `ganache-cli@v7.0.0-beta.0` as I just found the following command on [this](https://docs.nethereum.com/en/latest/ethereum-and-clients/ganache-cli/) page;

> ganache-cli --hostname:HTTP://192.168.1.8
```
Ganache CLI v7.0.0-beta.0 (ganache-core: 3.0.0-beta.0)

Available Accounts
==================
(0) 0x1c0b487289521347fbec4c111d77bc9e297e7bfd
(1) 0xb8d96b349e3ee06032e5e76ee576eab0033f7c26
(2) 0xad2c36a075a04285ee6458d152d658b8bce86a7e
(3) 0x8ab80b604bac03feee059aceb12b4cbf95491ee5
(4) 0xa914e454e16afede30f6a2970998008e82a7d23c
(5) 0xad1e4053d711ea1c3bc55712028229f2191c46d6
(6) 0x09be19d1deb9c0a6c3178b635ebe8463f21d3f0b
(7) 0xdb09a8f2d2a7d042814674342ba8de53f2b5092f
(8) 0xedd26769ca962bbff3936005d63c2ca9315c7fd3
(9) 0x1ac1674eecce99d662648c73555c8a4563ee0a53

Private Keys
==================
(0) 82cd5c009fb2938e897beb5654cc22c08ffaac702def3054843a624fe1963d7c
(1) 7b5f09f7df866d350f1e9495d4a869d11374038e01953df20608ca2d356b80e7
(2) f5c812e935be277305eacf245cb1b4330668f8b1198b72bbd04f3144b4c18936
(3) dc1939d31cd9354fcaf6e12e2970054e397a0d498d5446ec3319e5061f9a64f5
(4) e0836aae841c772fcc320e75372d11e143708384a2149c95488c6f69a3df196d
(5) 9ba5a0ec6ef77962647f1b7a3ab5d9a51dcb9c575a1f7402ee7c73dece6db055
(6) 9e057f3aebbcf56da758705f4cd7b867608a8029044500d7701fb0813abe9532
(7) 9675c18e1f728103111cd45ed3393947a6cd4ab0c249b47ba65c74c2460ba3df
(8) e76dfa6132b538184732cacedc21b442cbd744fa5a631484f00aba5150ed0908
(9) 0e4f2a6acc84d055aed3f39b8558def718ac6fe81fd068004dbc035913720e0d

HD Wallet
==================
Mnemonic:      start card economy spawn stuff palace afraid bridge air ginger orbit edge
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
```

But Now there are further 2 problems;

**1.**  The `ganache-cli@v7.0.0-beta.0` is very old as you said
**2.**  It's asking me `status not availible` whenever I deploy a contract using one of the above accounts.

![image](https://user-images.githubusercontent.com/41861952/65234781-ab265b00-daee-11e9-9a5a-4f4d5879c90d.png)

It will be better if `out of gas` error is resolved for `ganache-cli@6.7.0`.

**Comment by davidmurdoch** [comment]
@ZeeshanAhmadKhalil, Thanks for the detailed reproduction steps! @nicholasjpaterno found the root of the issue, and it is due to a too-low gas estimation that Ganache is sending to Remix. He's working on finding the solution now.

**Comment by ZeeshanAhmadKhalil** [comment]
Will I get the same problem if I use truffle' pet-shop instead of Remix to deploy the solidity smart contracts?

**Comment by davidmurdoch** [comment]
A temporary workaround while testing may be to perform additional work after the `transfer` call. This will sidestep the bug by increasing the gas required. Something like this will do the trick:

```
    function () external payable {
        address(the_instance).transfer(msg.value);
        the_instance.get_balance(); // <-- temporary ganache-core#486 workaround
    }
```

Of course, you wouldn't want to use something wasteful like this on Mainnet, but it may help with your testing while we patch this bug.

**Comment by ZeeshanAhmadKhalil** [comment]
Is the issue fixed? For me, it's giving the same `out of gas` error. I uninstalled and reinstalled `ganache-cli` globally. The `ganache-core 2.8.0` is also installed itself with `ganache-cli`.

**Comment by nicholasjpaterno** [comment]
@ZeeshanAhmadKhalil We've found and (I believe) fixed the issue!  Unfortunately the code is still currently in review before we can merge it into our `develop` branch.  It should find it's way into a release shortly thereafter!  If you have a chance and want to test the new fix now, checkout the branch `fix/gas-account-not-zero` on ganache-core.
