### ISSUE TITLE
"evm_mine" throws exception when Date.now() (number) is used. 

### ISSUE THREAD

**Issue by stonecoldpat** [trufflesuite/ganache-core#527]
## Expected Behavior
We want to fast-forward blocks using the current time in our test environment. e.g. mint 1000 blocks in a row. So we are using the "evm_mine" command. 

## Current Behavior
Periodically, it breaks all of our tests. We get the following exception: 

```
   Uncaught Error: Number can only safely store up to 53 bits
      at assert (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:6:21)
      at BN.toNumber (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:506:7)
      at Object.exports.bufferToInt (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/ethereumjs-util/src/index.ts:188:32)
      at Object.number (node_modules/ethereum-waffle/node_modules/ganache-core/lib/utils/to.js:122:18)
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/lib/blockchain_double.js:764:24
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/lib/database/blockserializer.js:45:9
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/async/dist/async.js:473:16
      at replenish (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/async/dist/async.js:1006:25)
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/async/dist/async.js:1016:9
      at eachLimit$1 (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/async/dist/async.js:3196:24)
      at Object.<anonymous> (node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/async/dist/async.js:1046:16)
      at Object.decode (node_modules/ethereum-waffle/node_modules/ganache-core/lib/database/blockserializer.js:29:11)
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/lib/database/leveluparrayadapter.js:40:21
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/level-sublevel/shell.js:102:12
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/level-sublevel/nut.js:122:19
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/encoding-down/index.js:57:5
      at /home/circleci/project/node_modules/ethereum-waffle/node_modules/ganache-core/node_modules/cachedown/index.js:53:7
      at processTicksAndRejections (internal/process/next_tick.js:74:9)

```
## Possible Solution
To get around it, we do: 
```
export async function mine(provider: JsonRpcProvider, noOfBlocks: number) {
    for (let i = 0; i < noOfBlocks; i++) {
        // sometime we get the following error:
        // Uncaught Error: Number can only safely store up to 53 bits
        // which is thrown down in ganache, in the past we solved this by minusing a large number
        // from Date.now(), but then that started failing.
        // https://github.com/trufflesuite/ganache-cli#custom-methods
        const time = Math.floor(Date.now() / 1000);
        await provider.send("evm_mine", [time]);
    }
}
```

Although the error seems to be the use of BigNumber.number() somewhere in Ganache. So it would be better to not turn it into a number but use string instead? 

## Steps to Reproduce (for bugs)

Simply write a test that calls the mineBlock() function. It will throw upon trying to do provider.send(). Sample code below. 

```
import { JsonRpcProvider } from "ethers/providers";

export const mineBlock = async (provider: JsonRpcProvider) => {
    await provider.send("evm_mine", [Date.now()]);
};
```

## Context
We want to fast-forward blocks using the current real-time clock. So this breaks our unit testing. 

## Your Environment
This happens across all our environments including OSX and CircleCI.

**Comment by nicholasjpaterno** [comment]
@stonecoldpat Thanks for raising this issue.  We'll take a look into the `Uncaught Error: Number can only safely store up to 53 bits` issue.  I'm curious what block numbers you're using in order to reach this exception!  Can you tell us more about your use case?

Ethereum blocktimes are only precise down to the second, so actually your workaround is the correct way to call `evm_mine`!  You're essentially truncating the milliseconds.  I've gone ahead and updated our documentation to make this more clear.

I'm going to keep this issue open for now so we can track your use case and perhaps better error handling around the `Uncaught Error`.
