### ISSUE TITLE
Cannot create an instance of a contract from another contract

### ISSUE THREAD

**Issue by saulgiordani** [trufflesuite/ganache-core#551]
I have 2 contracts, 1 factory and 1 entity: from the factory it's possible to create as many entities as wanted.
The code works on remix, but it fails with ganache

Here's the entity code:

```
pragma solidity ^0.4.17;

contract Entity {
    address public creator;
    address public manager;

    modifier restricted() {
        require(msg.sender == creator);
        _;
    }

    function Entity(address creatorAcc) public {
        creator = creatorAcc;
        manager = creatorAcc;
    }
}
```

and the factory code:
```
pragma solidity ^0.4.17;

import './entity.sol';

contract EntityFactory {
    Entity[] public deployedEntities;
    mapping(address => bool) public deployedEntitiesMap;

    function createEntity() public {
        Entity newEntity = new Entity(msg.sender);
        deployedEntitiesMap[newEntity] = true;
        deployedEntities.push(newEntity);
    }
}
```

The test:
```
const assert = require('assert');
const ganache = require('ganache-cli');
const Web3 = require('web3');
const web3 = new Web3(ganache.provider());

const compiledFactory = require('../build/contracts/EntityFactory.json');
const compiledEntity = require('../build/contracts/Entity.json');

let accounts;
let factory;
let rootEntityAddress;
let rootEntity;
let childEntityAddress;
let childEntity;

beforeEach(async () => {
  accounts = await web3.eth.getAccounts();

  factory = await new web3.eth.Contract(compiledFactory.abi)
    .deploy({ data: compiledFactory.bytecode })
    .send({ from: accounts[0], gas: '6721975' });

  // create rootEntity
  await factory.methods.createEntity().send({
    from: accounts[1],
    gas: '1000000'
  });
}
```
## Expected Behavior
In remix I'm able to deploy the factory and to create new entities from the factory using different accounts

## Current Behavior
the current console output:
```
Entities
    1) "before each" hook for "deploys a factory and an entity"


  0 passing (424ms)
  1 failing

  1) "before each" hook for "deploys a factory and an entity":
     c: VM Exception while processing transaction: revert
      at Function.c.fromResults (node_modules/ganache-cli/build/ganache-core.node.cli.js:2:157333)
      at A.processBlock (node_modules/ganache-cli/build/ganache-core.node.cli.js:17:121734)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

## Your Environment

* Version used: ganache-cli 6.9.1, web3 1.2.6
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Mac OS 10.13.6
* Link to your project:

**Comment by ghost** [comment]
why this issue was close?  here is the solution? I am falling on the same error.
I am using `vyper` and `create_forwarder_to` func to create new instance of contract but when I test it with ganache,
immediately returns a "rever" error. 
I am using `ganache v7.0.3 (@ganache/cli: 0.1.4, @ganache/core: 0.1.4)`

```
ProviderError: VM Exception while processing transaction: revert
    at HttpProvider.request (/Users/sugar/protocol/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at GanacheGasMultiplierProvider.request (/Users/sugar/protocol/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```

**Comment by davidmurdoch** [comment]
>  here is the solution

@MSUGARM Did you mean "where is the solution?" If you did, please open a new issue with steps to reproduce.
