### ISSUE TITLE
Latest ganache fails to start using node 14

### ISSUE THREAD

**Issue by nlordell** [trufflesuite/ganache-core#568]
Just wanted to report an issue I ran into, but it appears that the latest Ganache does not work with the very recently released node 14.

## Expected Behavior
Ganache to work in all its awesomeness.

## Current Behavior
Ganache fails to start. I assume this is not a `ganache-cli` issue as it also happens with `truffle develop`.

## Steps to Reproduce (for bugs)
1. `nvm use 14`
2. in a blank working directory `npm install ganache-cli`
3. `./node_modules/.bin/ganache-cli` errors with:
```
Ganache CLI v6.9.1 (ganache-core: 2.10.2)
Error: Callback was already called.
    at /var/home/nlordell/Developer/ganache-node-14/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:276
    at s.<anonymous> (/var/home/nlordell/Developer/ganache-node-14/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:2238)
    at s.emit (events.js:315:20)
    at s.destroy (/var/home/nlordell/Developer/ganache-node-14/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:712589)
    at finish (_stream_writable.js:681:14)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
4. `nvm use 13`
5. `./node_modules/.bin/ganache-cli`, everything works.

**Comment by nick** [comment]
I get this error too with Node 14, which is due to enter LTS (Long Term Support) a month from now.

```
/dshop/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358
                callback(err);
                ^
Error: Callback was already called.
    at /dshop/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:36
    at WriteStream.<anonymous> (/dshop/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358:17)
    at WriteStream.emit (events.js:314:20)
    at WriteStream.destroy (/dshop/node_modules/level-ws/level-ws.js:140:8)
    at finish (_stream_writable.js:670:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by davidmurdoch** [comment]
@nlordell, @nick I've released a beta version that supports Node 14. Can you try it out? https://github.com/trufflesuite/ganache-core/releases/tag/v2.12.2-beta.0

`npm install ganache-core@beta -E`

**Comment by nick** [comment]
Works great for me.... thanks 😊

**Comment by amihaz** [comment]
> @nlordell, @nick I've released a beta version that supports Node 14. Can you try it out? https://github.com/trufflesuite/ganache-core/releases/tag/v2.12.2-beta.0
> 
> `npm install ganache-core@beta -E`

worked for me
