### ISSUE TITLE
`header not found` error when starting ganache forking with infura RPC endpoint

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#615]
I'm not sure if this is specific to forking or infura, but periodically on v6.10.1 I receive the following error immediately on startup:

```
Ganache CLI v6.10.1 (ganache-core: 2.11.2)
Error: Returned error: header not found
    at Object.ErrorResponse (/home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2207407)
    at /home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2206279
    at /home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2193803
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Restarting will fix the issue fairly quickly. I'm wondering if this is related to #579 🤔 (doubt it though)

## Your Environment

* Version used: Ganache CLI v6.10.1 (ganache-core: 2.11.2)

**Comment by rishanb** [comment]
Similarish error - I've been trying to locate some kind of config file to see where "account 0xd0a8356c4889d2a9876c882a8bd9cc0ee7e4430b" comes from but have been unsuccessful so far.

`ganache-cli -f https://cloudflare-eth.com
Ganache CLI v6.11.0 (ganache-core: 2.12.1)
Error: The fork provider errored when checking the nonce for account 0xd0a8356c4889d2a9876c882a8bd9cc0ee7e4430b: Returned error: header not found
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1994078
    at Object._fireError (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:75947)
    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:119479)
    at n (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:2007203)
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1993001
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  data: null
}`

**Comment by seesemichaelj** [comment]
@rishanb ganache generates 10 accounts from a random mnemonic by default, even when you're forking. The screen just had not yet gotten to the point where it displays the accounts

I'm curious, is the error reproducible for you @rishanb? Does restarting no longer show the error?

**Comment by rishanb** [comment]
Apologies for the delay, ran into some weirdness and wanted to collect it all rather than creating confusion. It looks like the original issue thread might have now been combined here? 

I received the  original error above (header not found) when trying to run ganache-cli while forking from Cloudflare:
`ganache-cli -f https://cloudflare-eth.com`

Gave:
```
Ganache CLI v6.11.0 (ganache-core: 2.12.1)
Error: The fork provider errored when checking the nonce for account 0xcfd0f9c9dbb310707ab1ea60151e96b03daf1d32: Returned error: header not found
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1994078
    at Object._fireError (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:75947)
    at s (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:119479)
    at n (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:2007203)
    at /usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1993001
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  data: null
}
```

Retrying the same command provided the same error. I then uninstalled and reinstalled ganache-cli and got the same error with a different account address at the top.

If I leave out the "-f ..." part I get the callback error which made me aware that I need to revert my node version. I'm currently in the process of figuring out nvm and will report back if this error persists from node 12.

**Comment by rishanb** [comment]
Unfortunately, I'm getting the same issue with nvm 12 when making an initial attempt and retrying:

```
(base) ~ $ nvm use 12 && ganache-cli -f https://cloudflare-eth.com
Now using node v12.18.4 (npm v6.14.6)
Ganache CLI v6.11.0 (ganache-core: 2.12.1)
Error: The fork provider errored when checking the nonce for account 0x0f711c427f7d3497c1b457297820fe39dc911d37: Returned error: header not found
    at /Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1994078
    at Object._fireError (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:75947)
    at s (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:119479)
    at n (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:2007203)
    at /Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1993001
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  data: null
}
^C%                                                                                                                                 (base) ~  $ nvm use 12 && ganache-cli -f https://cloudflare-eth.com
Now using node v12.18.4 (npm v6.14.6)
Ganache CLI v6.11.0 (ganache-core: 2.12.1)
Error: The fork provider errored when checking the nonce for account 0xae3be88f190e877f05cc50952e6f201355b5a8ef: Invalid JSON RPC response: "502 Bad Gateway"
    at /Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1994078
    at Object._fireError (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:75947)
    at s (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:119479)
    at n (/Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:2007187)
    at /Users/rishanwins/.nvm/versions/node/v12.18.4/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:48:1993001
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
^C%                                                                                                                                 (base) ~/  $
```

**Comment by seesemichaelj** [comment]
> I'm glad to report the "header" issue is gone once running ganache from node 12:

Well both errors only occur when you are trying to fork a network, so glad that you're not hitting that code when you're not configured for forking haha

The second try you post when forking provides the error:

> Invalid JSON RPC response: "502 Bad Gateway"

Which sounds like an issue with the Cloudflare endpoint to some degree. I believe that error should be a brand new issue referring to cloudflare endpoint support since I can reproduce the `502 Bad Gateway` error consistently when using the cloudflare endpoint.

I'd suggest using Infura

---

Now the header not found error just coincidentally also showed up, which I do believe is separate from the cloudflare specific issue

**Comment by rishanb** [comment]
Thank you sir! Infura worked like a charm.

And as to my silliness above, in my last post I kinda of didn't scroll right and so missed the "header" error part of the first attempt...and incorrectly concluded it was some new nonce error ;p

So in summary: reverting to node 12 resolved all issues when not forking, and furthermore, forking from Infura resolved all forking issues. As you've pointed out, there appears to be an issue with Forking the Cloudflare ETH Endpoint.

**Comment by seesemichaelj** [comment]
Do note that Infura has a 128 block limit before needing to purchase the data archive add-on; you can read more about the limit here: https://infura.io/docs/ethereum/add-ons/archiveData. Depending on what you're using forking for, you may run into issues with the data archival.

Truffle Teams provides Sandboxes which are just cloud-hosted Ganache instances. Forking is available in Truffle Teams Sandboxes without the 128 block limit. Currently our free tier of Truffle Teams allows you to have 1 Sandbox, and you can currently choose forking in the free tier. Not sure if it'll always be available in the free tier, but it's free now! You can read more about Truffle Teams Sandboxes [in our docs](https://www.trufflesuite.com/docs/teams/deployments/sandboxes). You can sign up for a free Truffle Teams account at https://my.truffleteams.com

**Comment by dexcell** [comment]
Still exist when forking cloudflare, but not on infura. 
v6.12.1

**Comment by davidmurdoch** [comment]
@dexcell This might be because cloudflare doesn't support archive state.

**Comment by dexcell** [comment]
@davidmurdoch I see thanks

@seesemichaelj 
So truffle teams offer fork with archival data too? Right now i'm paying infura to test mainnetfork with archival data, i wish i saw this issue earlier.

**Comment by seesemichaelj** [comment]
@dexcell That's correct! At the current time, you can use your free sandbox to fork with archival data. [Check out our docs](https://www.trufflesuite.com/docs/teams/deployments/sandboxes) to see how to make a sandbox

**Comment by gnidan** [comment]
It's not clear what Ganache should do in these situations, but maybe this issue is one of better error reporting? I'll label this issue as such, since that's one path forward (i.e., augment the geth-provided error with additional detail on what's going wrong and possible ways to fix).

In the meantime, if anyone has ideas for handling this problem more robustly, we're all ears!

Thanks all.
