### ISSUE TITLE
Issues with Forking Cloudflare ETH Endpoint

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#644]
When forking `https://cloudflare-eth.com`, I get the error:

```
mike@darwin:~$ ganache-cli -f https://cloudflare-eth.com
Ganache CLI v6.11.1-alpha.1 (ganache-core: 2.13.0-alpha.2)
Error: The fork provider errored when checking net_version: Invalid JSON RPC response: "502 Bad Gateway"
    at web3.eth.net.getId (/home/mike/.nvm/versions/node/v10.20.1/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2099379)
    at Object._fireError (/home/mike/.nvm/versions/node/v10.20.1/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:75935)
    at s (/home/mike/.nvm/versions/node/v10.20.1/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:120922)
    at a (/home/mike/.nvm/versions/node/v10.20.1/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2114702)
    at Promise.all.then.e (/home/mike/.nvm/versions/node/v10.20.1/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2099002)
    at process._tickCallback (internal/process/next_tick.js:68:7
```

The URL does respond to a CURL request:

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' https://cloudflare-eth.com
{"jsonrpc":"2.0","result":"1","id":67}
```

This is also [seen in `v2.12.1`](https://github.com/trufflesuite/ganache-core/issues/615#issuecomment-704048686)

**Comment by davidmurdoch** [comment]
I can't reproduce. Can you try https://github.com/trufflesuite/ganache-cli/releases/tag/v6.11.1-beta.1 ?

**Comment by seesemichaelj** [comment]
I can no longer reproduce on `6.11.1-alpha.1`, `6.11.1-beta.1`, or `6.11.0`.

I'm guessing the issue was on Cloudflare's end and they fixed it. Closing this one! cc @rishanb
