### ISSUE TITLE
"invalid opcode" when reading chain id from inline assembly

### ISSUE THREAD

**Issue by PaulRBerg** [trufflesuite/ganache-core#654]
## Expected Behavior

The chain id should be accessible via inline assembly, [as this is a feature available since solidity 0.5.12][1].

## Current Behavior

The function that attempts to read the chain id fails with the following error:

```
Error: VM Exception while processing transaction: invalid opcode
  at HttpProvider.send (node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
  at /Users/paulrberg/Workspace/Pad/ganache-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:115:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/ganache-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:219:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/ganache-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:63:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at /Users/paulrberg/Workspace/Pad/ganache-invalid-opcode/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:41:21
  at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
  at EthersProviderWrapper.send (node_modules/@nomiclabs/buidler-ethers/src/ethers-provider-wrapper.ts:13:48)
  at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:439:31)
  at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
  at Object.next (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
  at /Users/paulrberg/Workspace/Pad/ganache-invalid-opcode/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:71
  at new Promise (<anonymous>)
  at __awaiter (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:17:12)
```

## Steps to Reproduce

1. Clone [paulrberg/ganache-invalid-opcode][2]
2. Install dependencies with yarn
3. Generate artifacts with `yarn run typechain`
4. Run the tests with `yarn run test` and get the same error as above

## Context

~I'm running Ganache via a [Hardhat][3] (formerly Buidler) plugin called [@nomiclabs/buidler-ganache][4], yet I don't see why Hardhat would be the culprit, so that's why I opened the issue here. If you disable the plugin and run the latest version of `ganache-cli` in a parallel console session, you get the exact same error.~ **Update**: this is actually a bug with Hardhat, see below.

Finally, I know about #515 and the plan to patch the bug in v3.0, but I hadn't seen people complaining that reading the chain id reverts, as it happens in my case.

## Your Environment

* @nomiclabs/buidler-ganache@1.3.3
* ganache-cli@6.9.0
* node@12.16.3
* macOS@10.15.7

[1]: https://ethereum.stackexchange.com/questions/56749/retrieve-chain-id-of-the-executing-chain-from-a-solidity-contract/76764#76764
[2]: https://github.com/paulrberg/ganache-invalid-opcode
[3]: https://github.com/nomiclabs/hardhat
[4]: https://github.com/nomiclabs/hardhat/tree/buidler/packages/buidler-ganache

**Comment by PaulRBerg** [comment]
Possibly related to [Error: VM Exception while processing transaction: invalid opcode when testing on different machines][1].

[1]: https://github.com/trufflesuite/ganache-cli/issues/397

**Comment by davidmurdoch** [comment]
Can you try ganache-cli@6.12.0?

**Comment by PaulRBerg** [comment]
I cannot reproduce the bug if I disable the `@nomiclabs/buidler-ganache` plugin, as in, there is no "invalid opcode" with either v6.9.0 or 6.12.0 It may be the case that Buidler has a bug, not Ganache. Sorry! I'll keep this issue open only for a few hours to confirm my findings.

**Comment by PaulRBerg** [comment]
Closing in favour of [nomiclabs/hardhat#952][1].

[1]: https://github.com/nomiclabs/hardhat/issues/952
