### ISSUE TITLE
WebSocket - requires non-standard message format

### ISSUE THREAD

**Issue by lukehedger** [trufflesuite/ganache-core#71]
## Expected Behavior
WebSocket should receive message and forward RPC request.

## Current Behavior
```
~/node_modules/ganache-cli/build/cli.node.js:95750
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONME

TypeError: connection.reject is not a function
    at WebSocketConnection.<anonymous> (~/node_modules/ganache-cli/build/webpack:/node_modules/ganache-core/lib/webSocketServer.js:50:1)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (~/node_modules/ganache-cli/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:548:1)
    at ~/node_modules/ganache-cli/build/cli.node.js:25355:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Possible Solution
It appears the WebSocket service [expects a non-standard message format](https://github.com/trufflesuite/ganache-core/blob/0a974718a1af06df30a993e6ff11005a5989335a/lib/webSocketServer.js#L45-L50) (dictated by the [`websocket` library](https://github.com/theturtle32/WebSocket-Node)).

This requirement should either be documented or, preferably, relaxed to allow a standard stringified message eg. `var payload = JSON.parse(message)`

## Steps to Reproduce
1. Install `ganache-cli@beta`
2. Run `ganache-cli`
3. Connect to WS and send a standard message
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>🔌</title>
  </head>
  <body>
    <script type="text/javascript">
      const socket = new WebSocket('ws://localhost:8545');

      socket.addEventListener('open', function (event) {
        socket.send('{"jsonrpc":"2.0","method":"eth_coinbase","params":[],"id":1}');
      });
    </script>
  </body>
</html>
```
4. Observe console error (shown above)

## Context
Trying to send an RPC request to Ganache WebSocket server.

## Your Environment
* Version used: Ganache CLI v6.1.0-beta.2 (ganache-core: 2.1.0-beta.1)

**Comment by lukehedger** [comment]
Ah this seems to be working now - not sure what was causing the bug tbh! I can see that the raw message is actually converted to the format `{ type, utf8Data }` so it couldn't have been that.

**Comment by llxxee** [comment]
I got the same error. Version used: Ganache CLI v6.2.3-beta.0 (ganache-core: 2.3.1)
